In [2]:
import pandas as pd
import os

In [3]:
df = pd.read_csv("Data/Raw/Características y composición del hogar.csv", sep= ";")
df

,DIRECTORIO,SECUENCIA_ENCUESTA,SECUENCIA_P,ORDEN,FEX_C,P6016,P1894,P6020,P6034,P6040,...,P1898,P1899,P3175,P1901,P1903,P1904,P1905,P1927,P3038,P3039
0,8369550,1,1,1,"472,1319014",1,3,2,1,45,...,10.0,5.0,7.0,10.0,6.0,0.0,7.0,6.0,1.0,2.0
1,8369550,2,1,2,"472,1319014",2,3,1,1,25,...,10.0,8.0,7.0,10.0,0.0,0.0,8.0,8.0,2.0,1.0
2,8369550,3,1,3,"472,1319014",3,2,2,1,16,...,10.0,10.0,10.0,10.0,0.0,0.0,10.0,10.0,NaN,NaN
3,8369550,4,1,4,"472,1319014",4,2,1,1,10,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,8369551,1,1,1,"308,8543189",1,3,2,1,62,...,7.0,4.0,7.0,8.0,6.0,2.0,8.0,7.0,1.0,2.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
235345,8489520,2,1,2,"19,04352805",2,3,2,1,31,...,10.0,10.0,10.0,10.0,1.0,0.0,9.0,9.0,1.0,2.0
235346,8489520,3,1,3,"19,04352805",3,1,2,1,8,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
235347,8489521,1,1,1,"19,04352805",1,3,1,1,31,...,10.0,9.0,9.0,10.0,1.0,0.0,10.0,9.0,2.0,1.0
235348,8489521,2,1,2,"19,04352805",2,3,2,1,32,...,10.0,10.0,9.0,9.0,1.0,1.0,10.0,9.0,1.0,2.0
235349,8489522,1,1,1,"10,35101672",1,3,1,1,45,...,8.0,8.0,8.0,8.0,1.0,0.0,10.0,6.0,2.0,1.0

In [4]:
df["DIRECTORIO"].duplicated().sum()

np.int64(148502)

In [5]:
datos_limpios = df.query("P6040 >= 18 and P753 == 2")
datos_limpios

,DIRECTORIO,SECUENCIA_ENCUESTA,SECUENCIA_P,ORDEN,FEX_C,P6016,P1894,P6020,P6034,P6040,...,P1898,P1899,P3175,P1901,P1903,P1904,P1905,P1927,P3038,P3039
4,8369551,1,1,1,"308,8543189",1,3,2,1,62,...,7.0,4.0,7.0,8.0,6.0,2.0,8.0,7.0,1.0,2.0
12,8369553,3,1,3,"268,976656",3,5,1,1,43,...,8.0,1.0,7.0,8.0,9.0,2.0,2.0,8.0,2.0,1.0
14,8369554,2,1,2,"353,9494419",2,3,1,1,64,...,8.0,5.0,9.0,7.0,3.0,3.0,8.0,6.0,2.0,1.0
32,8369561,1,1,1,"248,3358759",1,3,1,1,61,...,8.0,8.0,9.0,6.0,3.0,2.0,9.0,6.0,2.0,1.0
33,8369561,2,1,2,"248,3358759",2,3,2,1,61,...,8.0,6.0,10.0,7.0,3.0,3.0,10.0,8.0,1.0,2.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
235296,8489492,1,1,1,"6,900677816",1,3,2,1,25,...,9.0,8.0,8.0,9.0,2.0,2.0,9.0,7.0,1.0,2.0
235298,8489493,1,1,1,"17,92111851",1,3,1,1,37,...,9.0,9.0,9.0,9.0,2.0,2.0,10.0,7.0,2.0,1.0
235319,8489505,2,1,2,"8,62584727",2,3,2,1,33,...,8.0,8.0,8.0,8.0,1.0,1.0,10.0,8.0,1.0,2.0
235321,8489507,1,1,1,"8,62584727",1,3,2,1,42,...,8.0,9.0,8.0,9.0,0.0,0.0,10.0,7.0,1.0,2.0
235322,8489507,2,1,2,"8,62584727",2,3,2,1,24,...,8.0,8.0,8.0,9.0,0.0,0.0,10.0,7.0,1.0,2.0

In [6]:
datos_limpios = datos_limpios.drop(columns=["P3510S1","P3510S1A1","P3510S1A2","P3510S1A3"])
datos_limpios

,DIRECTORIO,SECUENCIA_ENCUESTA,SECUENCIA_P,ORDEN,FEX_C,P6016,P1894,P6020,P6034,P6040,...,P1898,P1899,P3175,P1901,P1903,P1904,P1905,P1927,P3038,P3039
4,8369551,1,1,1,"308,8543189",1,3,2,1,62,...,7.0,4.0,7.0,8.0,6.0,2.0,8.0,7.0,1.0,2.0
12,8369553,3,1,3,"268,976656",3,5,1,1,43,...,8.0,1.0,7.0,8.0,9.0,2.0,2.0,8.0,2.0,1.0
14,8369554,2,1,2,"353,9494419",2,3,1,1,64,...,8.0,5.0,9.0,7.0,3.0,3.0,8.0,6.0,2.0,1.0
32,8369561,1,1,1,"248,3358759",1,3,1,1,61,...,8.0,8.0,9.0,6.0,3.0,2.0,9.0,6.0,2.0,1.0
33,8369561,2,1,2,"248,3358759",2,3,2,1,61,...,8.0,6.0,10.0,7.0,3.0,3.0,10.0,8.0,1.0,2.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
235296,8489492,1,1,1,"6,900677816",1,3,2,1,25,...,9.0,8.0,8.0,9.0,2.0,2.0,9.0,7.0,1.0,2.0
235298,8489493,1,1,1,"17,92111851",1,3,1,1,37,...,9.0,9.0,9.0,9.0,2.0,2.0,10.0,7.0,2.0,1.0
235319,8489505,2,1,2,"8,62584727",2,3,2,1,33,...,8.0,8.0,8.0,8.0,1.0,1.0,10.0,8.0,1.0,2.0
235321,8489507,1,1,1,"8,62584727",1,3,2,1,42,...,8.0,9.0,8.0,9.0,0.0,0.0,10.0,7.0,1.0,2.0
235322,8489507,2,1,2,"8,62584727",2,3,2,1,24,...,8.0,8.0,8.0,9.0,0.0,0.0,10.0,7.0,1.0,2.0

In [7]:
datos_limpios.nunique().reset_index()

                 index      0
0           DIRECTORIO  26164
1   SECUENCIA_ENCUESTA     11
2          SECUENCIA_P      3
3                ORDEN     11
4                FEX_C  20920
..                 ...    ...
69               P1904     11
70               P1905     11
71               P1927     11
72               P3038      5
73               P3039      6

[74 rows x 2 columns]

In [8]:
datos_limpios.isnull().sum().reset_index()

                 index  0
0           DIRECTORIO  0
1   SECUENCIA_ENCUESTA  0
2          SECUENCIA_P  0
3                ORDEN  0
4                FEX_C  0
..                 ... ..
69               P1904  0
70               P1905  0
71               P1927  0
72               P3038  0
73               P3039  0

[74 rows x 2 columns]

In [10]:
nombre_archivo = "datos_limpios1.csv"
ruta_salida = os.path.join(os.getcwd(), nombre_archivo)
datos_limpios.to_csv(ruta_salida, index = False, encoding= "utf-8-sig")

# Bienestar y caracteristicas de la poblacion

## pregunta analitica

¿Cual es la edad que tiene el peor binestar y a que se dedican?

In [9]:
grupo = datos_limpios.groupby("P6040")[["P1927","P1899","P3175","P1898","P1897","P1896"]].mean().reset_index()
grupo

    P6040     P1927     P1899     P3175     P1898     P1897      P1896
0      18  7.642981  7.244367  7.816291  8.081456  8.396880  41.582322
1      19  7.623288  7.327055  7.813356  7.916096  8.520548  33.179795
2      20  7.676923  7.376068  7.823932  8.073504  8.538462  29.369231
3      21  7.521201  7.454064  7.579505  7.932862  8.420495  26.098940
4      22  7.551387  7.349103  7.592170  7.768352  8.474715  23.230016
..    ...       ...       ...       ...       ...       ...        ...
78     96  6.333333  5.777778  7.055556  7.500000  5.555556  52.833333
79     97  7.250000  6.625000  7.625000  7.750000  6.625000  17.625000
80     98  7.714286  7.571429  8.285714  7.142857  7.571429  33.857143
81     99  6.166667  4.666667  6.000000  6.333333  5.333333  19.500000
82    103  5.000000  4.000000  5.666667  6.333333  4.333333  68.000000

[83 rows x 7 columns]

# DIC variables
#### P6020 = Sexo al nacer
#### P6040 = Años Cumplidos
#### P1927 = Escalon de vida de 0-10
#### P1899 = Satisfaciion con el trabajo actual 0-10
#### P3175 = Satisfaccion con el tiempo libre 0-10
#### P1898 = Satisfaccion con la seguridad 0-10
#### P1897 = Satisfaccion con la salud 0-10
#### P1896 = Satisfaccion con el salario 0-10
#### P1895 = Satisfaciion con su vida en general 0-10 
#### P1905 = Consideracion de que las cosas que en su vida valen la pena 0-10
#### P6040 = siempre ha vivido en el municipio

In [18]:
variables = ["P6020","P1927","P1899","P3175","P1898","P1897","P1896"]
datos_limpios[variables].corr()

          P6020     P1927     P1899     P3175     P1898     P1897     P1896
P6020  1.000000  0.001954 -0.064710  0.007389 -0.013578 -0.035069  0.228261
P1927  0.001954  1.000000  0.440255  0.416394  0.358742  0.424602  0.000298
P1899 -0.064710  0.440255  1.000000  0.469557  0.397872  0.455282 -0.093826
P3175  0.007389  0.416394  0.469557  1.000000  0.413575  0.386149  0.065319
P1898 -0.013578  0.358742  0.397872  0.413575  1.000000  0.403865  0.042118
P1897 -0.035069  0.424602  0.455282  0.386149  0.403865  1.000000 -0.040547
P1896  0.228261  0.000298 -0.093826  0.065319  0.042118 -0.040547  1.000000

In [17]:
variables = ["P6020","P1927","P1899","P3175","P1898","P1897","P1896"]
datos_limpios[variables].corr(method= "spearman")

          P6020     P1927     P1899     P3175     P1898     P1897     P1896
P6020  1.000000  0.005300 -0.054150  0.008111 -0.013550 -0.037919  0.077632
P1927  0.005300  1.000000  0.486242  0.442339  0.384726  0.402602  0.331884
P1899 -0.054150  0.486242  1.000000  0.563654  0.487685  0.497968  0.387915
P3175  0.008111  0.442339  0.563654  1.000000  0.482608  0.433440  0.347994
P1898 -0.013550  0.384726  0.487685  0.482608  1.000000  0.466045  0.302776
P1897 -0.037919  0.402602  0.497968  0.433440  0.466045  1.000000  0.282443
P1896  0.077632  0.331884  0.387915  0.347994  0.302776  0.282443  1.000000