In [11]:
import pandas as pd
import os

In [194]:
df = pd.read_csv("../Data/Raw/Características y composición del hogar.csv", sep= ";")
df

,DIRECTORIO,SECUENCIA_ENCUESTA,SECUENCIA_P,ORDEN,FEX_C,P6016,P1894,P6020,P6034,P6040,...,P1898,P1899,P3175,P1901,P1903,P1904,P1905,P1927,P3038,P3039
0,8369550,1,1,1,"472,1319014",1,3,2,1,45,...,10.0,5.0,7.0,10.0,6.0,0.0,7.0,6.0,1.0,2.0
1,8369550,2,1,2,"472,1319014",2,3,1,1,25,...,10.0,8.0,7.0,10.0,0.0,0.0,8.0,8.0,2.0,1.0
2,8369550,3,1,3,"472,1319014",3,2,2,1,16,...,10.0,10.0,10.0,10.0,0.0,0.0,10.0,10.0,NaN,NaN
3,8369550,4,1,4,"472,1319014",4,2,1,1,10,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,8369551,1,1,1,"308,8543189",1,3,2,1,62,...,7.0,4.0,7.0,8.0,6.0,2.0,8.0,7.0,1.0,2.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
235345,8489520,2,1,2,"19,04352805",2,3,2,1,31,...,10.0,10.0,10.0,10.0,1.0,0.0,9.0,9.0,1.0,2.0
235346,8489520,3,1,3,"19,04352805",3,1,2,1,8,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
235347,8489521,1,1,1,"19,04352805",1,3,1,1,31,...,10.0,9.0,9.0,10.0,1.0,0.0,10.0,9.0,2.0,1.0
235348,8489521,2,1,2,"19,04352805",2,3,2,1,32,...,10.0,10.0,9.0,9.0,1.0,1.0,10.0,9.0,1.0,2.0
235349,8489522,1,1,1,"10,35101672",1,3,1,1,45,...,8.0,8.0,8.0,8.0,1.0,0.0,10.0,6.0,2.0,1.0

In [195]:
df["DIRECTORIO"].duplicated().sum()

np.int64(148502)

In [196]:
datos_limpios = df.query("P6040 >= 18")
datos_limpios

,DIRECTORIO,SECUENCIA_ENCUESTA,SECUENCIA_P,ORDEN,FEX_C,P6016,P1894,P6020,P6034,P6040,...,P1898,P1899,P3175,P1901,P1903,P1904,P1905,P1927,P3038,P3039
0,8369550,1,1,1,"472,1319014",1,3,2,1,45,...,10.0,5.0,7.0,10.0,6.0,0.0,7.0,6.0,1.0,2.0
1,8369550,2,1,2,"472,1319014",2,3,1,1,25,...,10.0,8.0,7.0,10.0,0.0,0.0,8.0,8.0,2.0,1.0
4,8369551,1,1,1,"308,8543189",1,3,2,1,62,...,7.0,4.0,7.0,8.0,6.0,2.0,8.0,7.0,1.0,2.0
5,8369552,1,1,1,"428,5162391",1,3,2,1,38,...,5.0,8.0,8.0,8.0,2.0,2.0,8.0,8.0,1.0,2.0
6,8369552,2,1,2,"428,5162391",2,3,1,1,49,...,5.0,8.0,8.0,8.0,2.0,3.0,8.0,8.0,2.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
235344,8489520,1,1,1,"19,04352805",1,3,1,1,32,...,10.0,10.0,9.0,9.0,0.0,1.0,9.0,9.0,2.0,1.0
235345,8489520,2,1,2,"19,04352805",2,3,2,1,31,...,10.0,10.0,10.0,10.0,1.0,0.0,9.0,9.0,1.0,2.0
235347,8489521,1,1,1,"19,04352805",1,3,1,1,31,...,10.0,9.0,9.0,10.0,1.0,0.0,10.0,9.0,2.0,1.0
235348,8489521,2,1,2,"19,04352805",2,3,2,1,32,...,10.0,10.0,9.0,9.0,1.0,1.0,10.0,9.0,1.0,2.0
235349,8489522,1,1,1,"10,35101672",1,3,1,1,45,...,8.0,8.0,8.0,8.0,1.0,0.0,10.0,6.0,2.0,1.0

In [197]:
datos_limpios = datos_limpios.drop(columns=["P3510S1","P3510S1A1","P3510S1A2","P3510S1A3"])
datos_limpios

,DIRECTORIO,SECUENCIA_ENCUESTA,SECUENCIA_P,ORDEN,FEX_C,P6016,P1894,P6020,P6034,P6040,...,P1898,P1899,P3175,P1901,P1903,P1904,P1905,P1927,P3038,P3039
0,8369550,1,1,1,"472,1319014",1,3,2,1,45,...,10.0,5.0,7.0,10.0,6.0,0.0,7.0,6.0,1.0,2.0
1,8369550,2,1,2,"472,1319014",2,3,1,1,25,...,10.0,8.0,7.0,10.0,0.0,0.0,8.0,8.0,2.0,1.0
4,8369551,1,1,1,"308,8543189",1,3,2,1,62,...,7.0,4.0,7.0,8.0,6.0,2.0,8.0,7.0,1.0,2.0
5,8369552,1,1,1,"428,5162391",1,3,2,1,38,...,5.0,8.0,8.0,8.0,2.0,2.0,8.0,8.0,1.0,2.0
6,8369552,2,1,2,"428,5162391",2,3,1,1,49,...,5.0,8.0,8.0,8.0,2.0,3.0,8.0,8.0,2.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
235344,8489520,1,1,1,"19,04352805",1,3,1,1,32,...,10.0,10.0,9.0,9.0,0.0,1.0,9.0,9.0,2.0,1.0
235345,8489520,2,1,2,"19,04352805",2,3,2,1,31,...,10.0,10.0,10.0,10.0,1.0,0.0,9.0,9.0,1.0,2.0
235347,8489521,1,1,1,"19,04352805",1,3,1,1,31,...,10.0,9.0,9.0,10.0,1.0,0.0,10.0,9.0,2.0,1.0
235348,8489521,2,1,2,"19,04352805",2,3,2,1,32,...,10.0,10.0,9.0,9.0,1.0,1.0,10.0,9.0,1.0,2.0
235349,8489522,1,1,1,"10,35101672",1,3,1,1,45,...,8.0,8.0,8.0,8.0,1.0,0.0,10.0,6.0,2.0,1.0

In [198]:
datos_limpios.nunique().reset_index()

                 index      0
0           DIRECTORIO  86759
1   SECUENCIA_ENCUESTA     16
2          SECUENCIA_P      6
3                ORDEN     16
4                FEX_C  57166
..                 ...    ...
69               P1904     11
70               P1905     11
71               P1927     11
72               P3038      5
73               P3039      6

[74 rows x 2 columns]

In [199]:
datos_limpios.isnull().sum().reset_index()

                 index  0
0           DIRECTORIO  0
1   SECUENCIA_ENCUESTA  0
2          SECUENCIA_P  0
3                ORDEN  0
4                FEX_C  0
..                 ... ..
69               P1904  0
70               P1905  0
71               P1927  0
72               P3038  0
73               P3039  0

[74 rows x 2 columns]

In [200]:
nombre_archivo = "datos_limpios1.csv"
ruta_salida = os.path.join(os.getcwd(), nombre_archivo)
datos_limpios.to_csv(ruta_salida, index = False, encoding= "utf-8-sig")

# Bienestar y caracteristicas de la poblacion

## pregunta analitica

¿Cómo varía el bienestar (este es medido como el promedio de satisfacción con la vida, salud, ingreso, seguridad, trabajo y tiempo libre) según el sexo y el estado civil de las personas?

# DIC variables
#### P6020 = Sexo al nacer  (NOMINAL)
#### P6040 = Años Cumplidos (NUMERICA-discreta)
#### P1927 = Escalon de vida de 0-10 (ordinal)
#### P1899 = Satisfaciion con el trabajo actual 0-10 (ordinal)
#### P3175 = Satisfaccion con el tiempo libre 0-10(ordinal)
#### P1898 = Satisfaccion con la seguridad 0-10(ordinal)
#### P1897 = Satisfaccion con la salud 0-10(ordinal)
#### P1896 = Satisfaccion con el ingreso 0-10(ordinal)
#### P1895 = Satisfaciion con su vida en general 0-10 (ordinal)
#### P1905 = Consideracion de que las cosas que en su vida valen la pena 0-10 (ordinal)
#### P6074 = siempre ha vivido en el municipio(NOMINAL)
#### P5502 = Estado civil (NOMINAL)

In [216]:
variables = ["P6020","P1927","P1899","P3175","P1898","P1897","P1896"]
datos_limpios[variables].corr()

          P6020     P1927     P1899     P3175     P1898     P1897     P1896
P6020  1.000000  0.006200 -0.057114  0.011953 -0.011626 -0.032957  0.203697
P1927  0.006200  1.000000  0.450947  0.441145  0.382159  0.447282 -0.001824
P1899 -0.057114  0.450947  1.000000  0.498272  0.416041  0.477189 -0.080358
P3175  0.011953  0.441145  0.498272  1.000000  0.453208  0.438546  0.064495
P1898 -0.011626  0.382159  0.416041  0.453208  1.000000  0.444097  0.040834
P1897 -0.032957  0.447282  0.477189  0.438546  0.444097  1.000000 -0.013700
P1896  0.203697 -0.001824 -0.080358  0.064495  0.040834 -0.013700  1.000000

In [217]:
variables = ["P6020","P1927","P1899","P3175","P1898","P1897","P1896"]
datos_limpios[variables].corr(method= "spearman")

          P6020     P1927     P1899     P3175     P1898     P1897     P1896
P6020  1.000000  0.006459 -0.046570  0.011543 -0.011120 -0.036824  0.063064
P1927  0.006459  1.000000  0.504024  0.465848  0.413626  0.436662  0.349631
P1899 -0.046570  0.504024  1.000000  0.593567  0.506936  0.529377  0.424453
P3175  0.011543  0.465848  0.593567  1.000000  0.521013  0.484896  0.381803
P1898 -0.011120  0.413626  0.506936  0.521013  1.000000  0.509768  0.322767
P1897 -0.036824  0.436662  0.529377  0.484896  0.509768  1.000000  0.316755
P1896  0.063064  0.349631  0.424453  0.381803  0.322767  0.316755  1.000000

In [218]:
var = ["P6020","P1927","P1899","P3175","P1898","P1897","P1896","P6040","P1895", "P1905","P5502"]
usable = datos_limpios[var]
usable

,P6020,P1927,P1899,P3175,P1898,P1897,P1896,P6040,P1895,P1905,P5502
0,2,6.0,5.0,7.0,10.0,10.0,99.0,45,8.0,7.0,5.0
1,1,8.0,8.0,7.0,10.0,10.0,8.0,25,10.0,8.0,4.0
4,2,7.0,4.0,7.0,7.0,7.0,4.0,62,5.0,8.0,3.0
5,2,8.0,8.0,8.0,5.0,8.0,8.0,38,8.0,8.0,2.0
6,1,8.0,8.0,8.0,5.0,8.0,9.0,49,8.0,8.0,2.0
...,...,...,...,...,...,...,...,...,...,...,...
235344,1,9.0,10.0,9.0,10.0,9.0,9.0,32,9.0,9.0,2.0
235345,2,9.0,10.0,10.0,10.0,10.0,10.0,31,10.0,9.0,2.0
235347,1,9.0,9.0,9.0,10.0,10.0,10.0,31,10.0,10.0,2.0
235348,2,9.0,10.0,9.0,10.0,9.0,10.0,32,10.0,10.0,2.0
235349,1,6.0,8.0,8.0,8.0,8.0,8.0,45,8.0,10.0,4.0

In [230]:
usable["P1896"] = usable["P1896"].replace(99, pd.NA)
usable["P1896"] = pd.to_numeric(usable["P1896"], errors="coerce")

In [219]:
usable.dtypes

P6020      int64
P1927    float64
P1899    float64
P3175    float64
P1898    float64
P1897    float64
P1896    float64
P6040      int64
P1895    float64
P1905    float64
P5502    float64
dtype: object

In [220]:
usable.isnull().sum().reset_index()

    index  0
0   P6020  0
1   P1927  0
2   P1899  0
3   P3175  0
4   P1898  0
5   P1897  0
6   P1896  0
7   P6040  0
8   P1895  0
9   P1905  0
10  P5502  0

In [221]:
usable.corr()

,P6020,P1927,P1899,P3175,P1898,P1897,P1896,P6040,P1895,P1905,P5502
P6020,1.000000,0.006200,-0.057114,0.011953,-0.011626,-0.032957,0.203697,-0.007824,-0.003467,0.010175,-0.031549
P1927,0.006200,1.000000,0.450947,0.441145,0.382159,0.447282,-0.001824,-0.018350,0.543273,0.498693,0.034364
P1899,-0.057114,0.450947,1.000000,0.498272,0.416041,0.477189,-0.080358,-0.063391,0.498499,0.394095,0.019832
P3175,0.011953,0.441145,0.498272,1.000000,0.453208,0.438546,0.064495,-0.004603,0.491595,0.409499,0.033068
P1898,-0.011626,0.382159,0.416041,0.453208,1.000000,0.444097,0.040834,-0.033269,0.440762,0.356627,0.022325
P1897,-0.032957,0.447282,0.477189,0.438546,0.444097,1.000000,-0.013700,-0.254702,0.559077,0.451255,-0.001462
P1896,0.203697,-0.001824,-0.080358,0.064495,0.040834,-0.013700,1.000000,-0.032997,0.020343,0.021759,0.018743
P6040,-0.007824,-0.018350,-0.063391,-0.004603,-0.033269,-0.254702,-0.032997,1.000000,-0.063750,-0.053751,0.073294
P1895,-0.003467,0.543273,0.498499,0.491595,0.440762,0.559077,0.020343,-0.063750,1.000000,0.530877,0.027783
P1905,0.010175,0.498693,0.394095,0.409499,0.356627,0.451255,0.021759,-0.053751,0.530877,1.000000,0.018798
P5502,-0.031549,0.034364,0.019832,0.033068,0.022325,-0.001462,0.018743,0.073294,0.027783,0.018798,1.000000

In [222]:
usable.describe().reset_index()

,index,P6020,P1927,P1899,P3175,P1898,P1897,P1896,P6040,P1895,P1905,P5502
0,count,172025.000000,172025.000000,172025.000000,172025.000000,172025.000000,172025.000000,172025.000000,172025.000000,172025.000000,172025.000000,172025.000000
1,mean,1.528882,7.655358,7.354739,7.585781,7.759564,7.839128,18.299154,45.844046,8.142224,8.550513,3.877611
2,std,0.499167,1.680805,2.201839,1.909613,1.948263,1.873769,30.725714,17.972662,1.634644,1.620444,1.624904
3,min,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,18.000000,0.000000,0.000000,1.000000
4,25%,1.000000,7.000000,6.000000,7.000000,7.000000,7.000000,6.000000,31.000000,7.000000,8.000000,2.000000
5,50%,2.000000,8.000000,8.000000,8.000000,8.000000,8.000000,7.000000,44.000000,8.000000,9.000000,4.000000
6,75%,2.000000,9.000000,9.000000,9.000000,9.000000,9.000000,9.000000,60.000000,9.000000,10.000000,5.000000
7,max,2.000000,10.000000,10.000000,10.000000,10.000000,10.000000,99.000000,108.000000,10.000000,10.000000,6.000000

In [223]:
usable.boxplot(column = "P6020")

In [232]:
variables_bienestar = ["P1895", "P1896", "P1897", "P1898", "P1899", "P3175"]
usable["bienestar"] = usable[variables_bienestar].mean(axis=1)
usable[["bienestar"] + variables_bienestar].head(20)

    bienestar  P1895  P1896  P1897  P1898  P1899  P3175
0    8.000000    8.0    NaN   10.0   10.0    5.0    7.0
1    8.833333   10.0    8.0   10.0   10.0    8.0    7.0
4    5.666667    5.0    4.0    7.0    7.0    4.0    7.0
5    7.500000    8.0    8.0    8.0    5.0    8.0    8.0
6    7.666667    8.0    9.0    8.0    5.0    8.0    8.0
9    6.666667    8.0    8.0    7.0    5.0    5.0    7.0
10   3.500000    7.0    1.0    2.0    3.0    1.0    7.0
11   4.000000    9.0    NaN    0.0    1.0    0.0   10.0
12   4.166667    7.0    0.0    2.0    8.0    1.0    7.0
13   7.500000    8.0    7.0    8.0    7.0    7.0    8.0
14   6.666667    7.0    5.0    6.0    8.0    5.0    9.0
15   8.166667    9.0    9.0    9.0    5.0    9.0    8.0
16   7.666667    9.0    9.0    8.0    5.0    7.0    8.0
17   5.166667    4.0    4.0    8.0    4.0    5.0    6.0
18   5.000000    7.0    3.0    5.0    4.0    3.0    8.0
19   6.666667    7.0    4.0   10.0    3.0    8.0    8.0
20  10.000000   10.0   10.0   10.0   10.0   10.0   10.0
21   9.166667   10.0    8.0   10.0    9.0    8.0   10.0
22   9.333333    9.0    7.0   10.0   10.0   10.0   10.0
23   7.333333    9.0    8.0    8.0    5.0    7.0    7.0

In [233]:
usable["bienestar"] = pd.to_numeric(usable["bienestar"], errors="coerce")
usable["P1896"].describe()

count    150344.000000
mean          6.661343
std           2.363695
min           0.000000
25%           5.000000
50%           7.000000
75%           8.000000
max          10.000000
Name: P1896, dtype: float64

In [234]:
usable[["P1895","P1896","P1897","P1898","P1899","P3175","bienestar"]].dtypes

P1895        float64
P1896        float64
P1897        float64
P1898        float64
P1899        float64
P3175        float64
bienestar    float64
dtype: object

In [235]:
usable["bienestar"].describe()

count    172025.000000
mean          7.576926
std           1.479549
min           0.000000
25%           6.666667
50%           7.666667
75%           8.600000
max          10.000000
Name: bienestar, dtype: float64

In [236]:
estado_civil = (
                usable.groupby("P5502")
                .agg(bienestar_promedio = ("bienestar", "mean"),
                total_personas = ("bienestar", "count"))
)

genero = (
                usable.groupby("P6020")
                .agg(bienestar_promedio = ("bienestar", "mean"),
                total_personas = ("bienestar", "count"))
)

estado_civil, genero

(       bienestar_promedio  total_personas
 P5502
 1.0              7.740199            3651
 2.0              7.569877           56869
 3.0              7.229845           10644
 4.0              7.478527           22337
 5.0              7.608327           42767
 6.0              7.698695           35757,
        bienestar_promedio  total_personas
 P6020
 1                7.628125           81044
 2                7.531319           90981)